-- Initial schema for the prescription tracker (milestone 1).
--
-- Conventions:
--   * Identifiers are TEXT UUIDs generated by the application layer.
--   * All date/time columns are TEXT holding ISO 8601 strings with a
--     timezone offset. The schema only enforces NOT NULL; full ISO 8601
--     with-timezone validation lives in the validation layer (milestone 2).
--   * Prescription rows are immutable after creation; the only permitted
--     mutations are explicit status transitions recorded in
--     status_transitions. Discontinuation requires a reason.

CREATE TABLE IF NOT EXISTS patients (
    id         TEXT PRIMARY KEY,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id                 TEXT PRIMARY KEY,
    patient_id         TEXT NOT NULL REFERENCES patients(id),
    doctor_id          TEXT NOT NULL REFERENCES doctors(id),
    medicine_name      TEXT NOT NULL,
    dosage_amount      REAL NOT NULL CHECK (dosage_amount > 0),
    dosage_unit        TEXT NOT NULL,
    frequency          TEXT NOT NULL,
    start_date         TEXT NOT NULL,
    end_date           TEXT CHECK (end_date IS NULL OR end_date > start_date),
    status             TEXT NOT NULL DEFAULT 'active'
                       CHECK (status IN ('active', 'completed', 'discontinued')),
    discontinue_reason TEXT,
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS status_transitions (
    id              TEXT PRIMARY KEY,
    prescription_id TEXT NOT NULL REFERENCES prescriptions(id),
    from_status     TEXT NOT NULL,
    to_status       TEXT NOT NULL CHECK (to_status IN ('active', 'completed', 'discontinued')),
    reason          TEXT,
    transitioned_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS dose_logs (
    id              TEXT PRIMARY KEY,
    prescription_id TEXT NOT NULL REFERENCES prescriptions(id),
    event           TEXT NOT NULL CHECK (event IN ('taken', 'skipped')),
    logged_at       TEXT NOT NULL
);

-- One active prescription per medicine per patient. Historical
-- (completed / discontinued) rows are exempt so a patient can be
-- re-prescribed the same medicine after a course ends.
CREATE UNIQUE INDEX IF NOT EXISTS one_active_per_medicine
    ON prescriptions(patient_id, medicine_name)
    WHERE status = 'active';

-- Query-SLO indexes: (patient_id, status) for active/historical filters
-- and (patient_id, start_date DESC) for history listing.
CREATE INDEX IF NOT EXISTS idx_rx_patient_status
    ON prescriptions(patient_id, status);

CREATE INDEX IF NOT EXISTS idx_rx_patient_start
    ON prescriptions(patient_id, start_date DESC);

CREATE INDEX IF NOT EXISTS idx_dose_logs_rx
    ON dose_logs(prescription_id, logged_at);